name: CI
on:
    - push
jobs:
    execute:
        name: Test and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the current repository
              uses: actions/checkout@master
              with:
                  fetch-depth: 0
            - name: Setup NodeJS 16
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
            - name: Install dependencies
              run: npm i
            - name: "Autofix"
              run: "npm run autofix"
            - name: Run Tests
              run: npm run syntax