name: "📚 Build Docs"
on:
  push: 
    paths-ignore:
      - 'docs/**'
jobs:
  execute:
    name: "🔨 Build Docs"
    runs-on: "ubuntu-latest"
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 🔨 Build Docs
        run: |
          npm
          npm run docs